language: ruby
bundler_args: --without development --path=~/.bundle
rvm:
  - ruby-2.0.0-p247
before_install:
  - 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc'
  - gem install bundler
before_script:
  - bundle exec rake db:create db:migrate
env:
  global:
  - STORE_NAME="traviscistore"
  - MYSQL_DB_PASSWORD="1234qwer"
  - MAILCHIMP_API_KEY=2ccd3a737e02e3681d799a276cc848c5-us10
