language: ruby
bundler_args: --without development --path=~/.bundle
rvm:
  - ruby-2.1.2
before_install:
  - 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc'
  - gem install bundler
before_script:
  - mysql -e 'create database traviscistore_test'
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
env:
  global:
  - STORE_NAME="traviscistore"
  #Dummy Key
  - MAILCHIMP_API_KEY=2ccd3a737e02e3681d799a276cc848c5-us10
after_success:
  — "docker login -e=\"$DOCKER_EMAIL\" -u=\"$DOCKER_USERNAME\" -p=\"$DOCKER_PASSWORD\""
  — "docker build -t \"lorcanoeire/base-spree-store:$TRAVIS_COMMIT\" ."
  — "docker push lorcanoeire/base-spree-store:$TRAVIS_COMMIT"
notifications:
  email:
    on_success: always
