sudo: required

language: ruby

bundler_args: --without development --path=~/.bundle

rvm:
  - ruby-2.1.2

before_install:
  - 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc'
  - gem install bundler

before_script:
  - mysql -e 'create database traviscistore_test'

script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace

services:
  - docker

env:
  global:
  - STORE_NAME="traviscistore"

notifications:
  email:
    on_success: always

after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=lorcanoeire/base-spree-store
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
