---
development:
  adapter: mysql2
  database: <%= ENV['STORE_NAME'] %>_dev
  pool: 5
  timeout: 5000
  username: root
  password: <%= ENV['MYSQL_DB_PASSWORD'] %>
  host: <%= ENV['MYSQL_DB_HOST'] %>

test:
  adapter: mysql2
  database: <%= ENV['STORE_NAME'] %>_test
  pool: 5
  timeout: 5000
  username: root
  password: <%= ENV['MYSQL_DB_PASSWORD'] %>
  host: <%= ENV['MYSQL_DB_HOST'] %>

production:
  adapter: mysql2
  database: <%= ENV['STORE_NAME'] %>_production
  pool: 5
  timeout: 5000
  username: root
  password: <%= ENV['MYSQL_DB_PASSWORD'] %>
  host: <%= ENV['MYSQL_DB_HOST'] %>

